version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
